<?php

return [
    'vehicle' => [
        //        'vehicle_id' => 'number',
        'status' => 'active_deactive',
        'vehicle_type' => 'string',
        //        'posting_class' => 'string',
        'dock_high' => 'yes_no',
        'payload' => 'number',
        'box_dims_length' => 'number',
        'box_dims_width' => 'number',
        'box_dims_height' => 'number',
        //        'door_dims_width' => 'number',
        //        'door_dims_height' => 'number',
        'gross_veh_weight' => 'number',
        //        'door_type' => 'string',
        'air_ride' => 'yes_no',
        //        'temp_control' => 'yes_no',
        'left_gate' => 'yes_no',
        //        'domicile' => 'string',
        //        'can_cross_border' => 'yes_no',
        'team' => 'yes_no',
        //        'dispatch_board' => 'string',
        //        'communication_system' => 'string',
        //        'omnitracs_unit_no' => 'number',
        //        'ivg_unit' => 'yes_no',
        //        'needs_trailer' => 'yes_no',
        'e_trac' => 'yes_no',
        'trailer_tracking' => 'yes_no',
        //        'door_sensors' => 'yes_no',
        //        'panis_button' => 'yes_no',
        //        'enable_for_nlm' => 'yes_no',
        //        'nlm_truck_size' => 'number',
        //        'nlm_truck_class' => 'number',
        //        'fuel_capacity' => 'number',
        'fuel_source' => 'string',
        //        'mpg' => 'number',
        //        'date_hired' => 'datepicker',
        'who_hired' => 'string',
        //        'hazmat_certified' => 'yes_no',
        //        'partial_space_available' => 'number',
        'date_retired' => 'datepicker',
        //        'retired_by' => 'string',
        'vin_no' => 'string',
        'license_plate' => 'string',
        'license_state' => 'string',
        'vehicle_make' => 'string',
        'vehicle_model' => 'string',
        'vehicle_year' => 'number',
        'vehicle_color' => 'string',
        'no_of_axles' => 'number',
        //        'unladen_weight' => 'number',
        //        'purchase_cost' => 'number',
        //        'purchase_date' => 'datepicker',
        //        'lease_exp_date' => 'datepicker',
        //        'comments' => 'text_area',
        //        'dispatch_note' => 'text_area',
        //        'availability_note' => 'text_area',
        //        'automatically_post_truck' => 'yes_no',
        'lic_plate_expiry_date' => 'datepicker',
        //        'last_pm_date' => 'datepicker',
        //        'next_pm_date' => 'datepicker',
        //        'insurance_type' => 'string',
        'insurance_expires' => 'datepicker',
        //        'insurance_carrier' => 'string',
        //        'non_truck_insurance_type' => 'string',
        //        'non_truck_insurance_expires' => 'datepicker',
        //        'non_truck_insurance_carrier' => 'string',
        'emission_test_due' => 'datepicker',
        'last_monthly_insp' => 'datepicker',
        'previous_dot_inspection_date' => 'datepicker',
        'next_dot_inspection_date' => 'datepicker',
        //        'fuel_tax_exempt' => 'yes_no',
        //        'fast_truck' => 'yes_no',
        //        'fast_transponder_no' => 'string',
        'ifta_sticker_no' => 'string',
        'ifta_sticker_expires' => 'datepicker',
        'odometer_when_hired' => 'number',
        'odometer_when_retired' => 'number',
        //        'refeer_mode' => 'string',
    ],
    'driver' => [
        'unit_number' => 'string',
        'first_name' => 'string',
        'last_name' => 'string',
        'mobile_number' => 'string',
        'email' => 'email',
        'address_one' => 'string',
        //        'address_two' => 'string',

        'city' => 'string',
        'state' => 'string',
        'zip' => 'string',
        'date_of_birth' => 'datepicker',

        //        'home_phone' => 'string',
        'social_security_number' => 'string',
        'emergency_contact' => 'string',
        //        'fax' => 'string',
        //        'domicile' => 'string',

        'can_cross_border' => 'yes_no',
        'hired_date' => 'datepicker',

        'payroll_class' => 'string',
        //        'pay_target' => 'string',
        //        'target_attained' => 'string',
        //        'active_payroll' => 'yes_no',
        //        'print_1099' => 'yes_no',
        //        'mail_paycheck' => 'yes_no',
        //        'billed_mileage_type' => 'string',

        //        'work_visa' => 'string',
        //        'work_visa_expires' => 'string',

        //        'pay_currency' => 'string',
        'last_physical_date' => 'datepicker',
        'next_physical_date' => 'datepicker',
        //        'hazmat_certificate' => 'string',
        //        'trained_hazmat_date' => 'datepicker',
        //        'expires_hazmat_date' => 'datepicker',

        //        'license_type' => 'string',
        //        'license_state' => 'string',
        'license_number' => 'string',
        'license_class' => 'string',
        //        'driving_since' => 'string',
        'drivers_lic_expires' => 'string',

        //        'abstract_due' => 'string',
        //        'last_review_date' => 'datepicker',
        //        'next_review_date' => 'datepicker',
        //        'workres_comp_expires' => 'string',

        //        'passed_security_clearance' => 'yes_no',
        //        'passed_security_clearance_date' => 'datepicker',

        //        'joined_company_insurance' => 'string',
        //        'terminated_company_insurance' => 'string',

        //        'fast_placard' => 'yes_no',
        //        'fast_placard_no' => 'string',

        //        'tas_certified' => 'yes_no',
        //        'tas_ref_no' => 'string',
        //        'tas_certified_date' => 'datepicker',
        //        'tas_expiry_date' => 'datepicker',

        //        'twic_certified' => 'yes_no',
        //        'twic_ref_no' => 'string',
        //        'twic_certified_date' => 'datepicker',
        //        'twic_expiry_date' => 'datepicker',

        //        'random_drug_test' => 'yes_no',
        //        'tanker_endorsement' => 'yes_no',
    ],
    'work' => [
        'pieces' => 'string',
        'weight' => 'string',
        'miles' => 'string',
        //        'brokerage_name' => 'string',
        /*'pickup_address' => 'string',*/
        //        'company_name' => 'string',
        /*'drop_address' => 'string',*/
        'admin_load_notes' => 'text_area',
    ],
    'biding' => [
        'pieces' => 'string',
        'weight' => 'string',
        'miles' => 'string',
        /*'pickup_address' => 'string',*/
        'company_name' => 'string',
        /*'drop_address' => 'string',*/
        'admin_load_notes' => 'text_area',
    ],
    'bill' => [
        'name' => 'string',
        'amount' => 'number',
        'pay_date' => 'datepicker',
        // 'country' => 'string',
        'admin_note' => 'text_area',
    ],
    'payroll' => [
        'transaction_number' => 'string',
        'amount' => 'number',
        'date' => 'datepicker'
    ],
    'customer' => [
        'name' => 'string',
        'business_address' => 'string',
        'city_st_zip' => 'string',
        'phone_number' => 'string',
        'ext' => 'string',
        'email' => 'string',
        'usdot' => 'string',
        'broker_mc' => 'string',
        'admin_note' => 'text_area',
    ],
    'carrier' => [
        'name' => 'string',
        'business_address' => 'string',
        'city_st_zip' => 'string',
        'phone_number' => 'string',
        'ext' => 'string',
        'email' => 'string',
        'usdot' => 'string',
        'broker_mc' => 'string',
        //        'admin_note' => 'text_area',
    ],
    'work_status' => [
        'title' => 'string',
    ],
    'us_state' => [
        "Alaska",
        "Alabama",
        "Arkansas",
        "American Samoa",
        "Arizona",
        "California",
        "Colorado",
        "Connecticut",
        "District of Columbia",
        "Delaware",
        "Florida",
        "Georgia",
        "Guam",
        "Hawaii",
        "Iowa",
        "Idaho",
        "Illinois",
        "Indiana",
        "Kansas",
        "Kentucky",
        "Louisiana",
        "Massachusetts",
        "Maryland",
        "Maine",
        "Michigan",
        "Minnesota",
        "Missouri",
        "Mississippi",
        "Montana",
        "North Carolina",
        "North Dakota",
        "Nebraska",
        "New Hampshire",
        "New Jersey",
        "New Mexico",
        "Nevada",
        "New York",
        "Ohio",
        "Oklahoma",
        "Oregon",
        "Pennsylvania",
        "Puerto Rico",
        "Rhode Island",
        "South Carolina",
        "South Dakota",
        "Tennessee",
        "Texas",
        "Utah",
        "Virginia",
        "Virgin Islands",
        "Vermont",
        "Washington",
        "Wisconsin",
        "West Virginia",
        "Wyoming"
    ]
];
